name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1.2.3
      with:
        version: master
    - run: zig build test-no-render
