name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - uses: goto-bus-stop/setup-zig@v1.2.3
      with:
        version: master
    - run: zig build test-no-render -Drelease-fast
    - run: zig build simple-core -Drelease-fast
